// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7nWDDzMowAEXR60xMTss53HiXIq3IBHg',
    appId: '1:654929189360:web:5e7a643b6f4668a63e6535',
    messagingSenderId: '654929189360',
    projectId: 'tickup-301125',
    authDomain: 'tickup-301125.firebaseapp.com',
    storageBucket: 'tickup-301125.firebasestorage.app',
    measurementId: 'G-7094ZHX3ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGR_BEk6kLAjDHQ9oKsQ44AfX5bVksTNA',
    appId: '1:654929189360:android:e1d94f54e14ace713e6535',
    messagingSenderId: '654929189360',
    projectId: 'tickup-301125',
    storageBucket: 'tickup-301125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbx0IfAVV3BNULwKKHT1oqXiCUtjIMLsA',
    appId: '1:654929189360:ios:d6b785ebd6e0fb943e6535',
    messagingSenderId: '654929189360',
    projectId: 'tickup-301125',
    storageBucket: 'tickup-301125.firebasestorage.app',
    iosBundleId: 'com.tickup.tickup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbx0IfAVV3BNULwKKHT1oqXiCUtjIMLsA',
    appId: '1:654929189360:ios:d6b785ebd6e0fb943e6535',
    messagingSenderId: '654929189360',
    projectId: 'tickup-301125',
    storageBucket: 'tickup-301125.firebasestorage.app',
    iosBundleId: 'com.tickup.tickup',
  );

  static const windows = FirebaseOptions(
    apiKey: 'AIzaSyB7nWDDzMowAEXR60xMTss53HiXIq3IBHg',
    appId: '1:654929189360:web:d78b01fa723fdda03e6535',
    messagingSenderId: '654929189360',
    projectId: 'tickup-301125',
    authDomain: 'tickup-301125.firebaseapp.com',
    storageBucket: 'tickup-301125.firebasestorage.app',
    measurementId: 'G-K1H1MDLQYQ',
  );
}
